export type Sentiment = 'positive' | 'negative' | 'mixed'
export type Category = '程式開發' | '寫作' | '圖像生成' | '影片生成' | '自動化' | '語音'
export type SortKey = 'hot' | 'rising' | 'discussed'

export interface Quote {
  text: string
  source: string
  sentiment: Sentiment
  date: string
  url?: string
  author?: string
}

export interface Competitor {
  name: string
  count: number
}

export interface ToolSources {
  reddit: number
  hn: number
  github: number
  v2ex?: number
  juejin?: number
}

export interface SentimentBreakdown {
  positive: number
  negative: number
  mixed: number
  total: number
}

export interface Tool {
  rank: number
  prevRank: number
  slug: string
  name: string
  initials: string
  accent: string
  description: string
  category: Category
  score: number
  delta: number
  discussions: number
  growth: string
  sources: ToolSources
  audiences: string[]
  useCases: string[]
  painPoints: string[]
  pricingFeel: string
  quotes: Quote[]
  competitors: Competitor[]
  trend: number[]
  sentimentBreakdown?: SentimentBreakdown
  website?: string
  logo_url?: string
  features?: string[]
  recentUpdates?: string[]
  docsUrl?: string
  radarScores?: number[]
  communitySummary?: string
  pricingDescription?: string
  depthDescription?: string
  aiReview?: string
}

export interface SortOption {
  id: SortKey
  label: string
}

export const TOOLS: Tool[] = [
  {
    rank: 0, prevRank: 0,
    slug: 'claude-code', name: 'Claude Code', initials: 'CC',
    accent: 'oklch(0.62 0.14 35)', category: '程式開發',
    website: 'https://claude.ai/code',
    logo_url: 'https://www.google.com/s2/favicons?domain=claude.ai&sz=64',
    docsUrl: 'https://code.claude.com/docs/en/overview',
    description: 'Anthropic 推出的 agentic 程式助理，直接在終端機操作檔案、執行指令、提交 PR',
    pricingDescription: '需 Claude Pro（$20/mo）或 Max（$100/mo），API 用戶按 token 計費。Agent 模式單次任務約消耗 $0.5–5，重度使用費用高。',
    features: [
      '自動化繁瑣工作：補寫測試、修 lint 錯誤、解決 merge conflict、更新套件',
      '用自然語言描述需求，Claude Code 規劃方案、跨檔案寫程式並驗證結果',
      '直接與 git 整合：暫存變更、撰寫 commit message、建立 branch 與 PR',
      'MCP 支援：連接 Google Drive、Jira、Slack 或自訂工具',
      'CLAUDE.md 設定專案規範、架構決策與偏好套件，每次 session 自動載入',
      '多 Agent 並行：spawn 多個 Claude Code agent 同時處理不同子任務',
      'Routines：排程重複任務，在 Anthropic 托管基礎設施上執行',
      'CLI 可組合使用：pipe log、在 CI 中執行、與其他工具串接',
    ],
    recentUpdates: [
      '2026/05 — 推出 Routines 排程功能（Anthropic 托管 + 本機兩種模式）',
      '2026/05 — Sub-agents 支援跨 session 的 lead agent 協調架構',
      '2026/04 — 加入 Hooks 機制，可在工具呼叫前後執行自訂腳本',
      '2025/05 — 正式公開發布（GA），結束 Beta',
    ],
    score: 0, delta: 0, discussions: 0, growth: '',
    sources: { reddit: 0, hn: 0, github: 0 },
    audiences: [], useCases: [], painPoints: [],
    pricingFeel: '', quotes: [], competitors: [], trend: [],
  },
  {
    rank: 0, prevRank: 0,
    slug: 'cursor', name: 'Cursor', initials: 'Cu',
    accent: 'oklch(0.55 0.18 265)', category: '程式開發',
    website: 'https://cursor.com',
    logo_url: 'https://www.google.com/s2/favicons?domain=cursor.com&sz=64',
    docsUrl: 'https://docs.cursor.com',
    description: '以 AI 為核心的程式編輯器，支援跨檔案編輯、Composer 模式與 agent 自動完成任務',
    pricingDescription: '免費版每月 500 次 fast request。Pro $20/mo，含無限 slow request 與 500 次 fast。Business $40/mo 加上團隊管理功能。',
    features: [
      'Agents：自動執行任務、建置、測試並 demo 功能',
      'Tab：專門化的自動補全模型，預測下一步行動',
      'Composer 2.5：AI 協作編寫程式碼，支援完整 codebase 理解與語意搜尋',
      'BugBot（Code Review）：程式碼審查，自動偵測潛在 bug',
      'Cloud Agents：在雲端運行的 agent，支援多 repo 或無 repo 配置',
      'Cursor Automations：自動化重複任務，整合 Jira、Slack、GitHub PR',
    ],
    recentUpdates: [
      '2026/05/20 — Cursor Automations 改進（v3.5），支援多 repo 配置',
      '2026/05/19 — 整合 Jira，可在工作項目中直接指派 Cursor Agent',
      '2026/05/18 — Composer 2.5 推出，智能與行為大幅提升',
      '2026/05/13 — 全螢幕 Tabs 與緊湊聊天模式（v3.4）',
    ],
    score: 0, delta: 0, discussions: 0, growth: '',
    sources: { reddit: 0, hn: 0, github: 0 },
    audiences: [], useCases: [], painPoints: [],
    pricingFeel: '', quotes: [], competitors: [], trend: [],
  },
  {
    rank: 0, prevRank: 0,
    slug: 'trae', name: 'Trae', initials: 'Tr',
    accent: 'oklch(0.55 0.16 200)', category: '程式開發',
    website: 'https://trae.ai',
    logo_url: 'https://www.google.com/s2/favicons?domain=trae.ai&sz=64',
    docsUrl: 'https://docs.trae.ai',
    description: 'ByteDance 推出的 AI IDE，SOLO agent 自主完成整個開發任務，SWE-bench Verified 排行第一',
    pricingDescription: '目前完全免費，ByteDance 補貼所有模型費用（含 Claude 4）。正式商業化時程未定，現為搶市佔策略。',
    features: [
      'TRAE SOLO：使用者定義任務，AI 自主處理其餘所有步驟',
      'Cue-Pro：程式碼編輯預測的全局視角，預覽 AI 下一步計畫',
      'Agent Skills：可自訂 Rules + Tools 定義你的 Agent 行為',
      'Max Mode：最高效能模式，使用頂級模型處理複雜任務',
      'SOLO Mobile App：在手機上啟動和監控 Agent 任務',
      'SWE-bench Verified #1：以 Claude 4 達到業界最高評分',
    ],
    recentUpdates: [
      '2026/05/06 — 推出 TRAE SOLO Mobile App',
      '2026/03/31 — The New SOLO 重大更新',
      '2025/12/29 — Cue-Pro 技術深度更新',
      '2025/11/04 — TRAE SOLO 正式 GA 發布',
    ],
    score: 0, delta: 0, discussions: 0, growth: '',
    sources: { reddit: 0, hn: 0, github: 0 },
    audiences: [], useCases: [], painPoints: [],
    pricingFeel: '', quotes: [], competitors: [], trend: [],
  },
  {
    rank: 0, prevRank: 0,
    slug: 'windsurf', name: 'Windsurf', initials: 'Wi',
    accent: 'oklch(0.55 0.15 165)', category: '程式開發',
    website: 'https://windsurf.com',
    logo_url: 'https://www.google.com/s2/favicons?domain=windsurf.com&sz=64',
    docsUrl: 'https://docs.windsurf.com/windsurf/getting-started',
    description: 'Codeium 推出的 AI 編輯器，以 Cascade agent 模式實現深度上下文感知的多步驟編程',
    pricingDescription: '免費版含每月 Windsurf Credits（有限），Pro $15/mo 含更多 Credits，Team $35/人/mo。Credits 耗盡需另購。',
    features: [
      'Cascade：深度感知整個 codebase 的 agentic 工作流，可自主執行多步驟任務',
      'Windsurf Tab：預測下一步編輯行為，支援跨檔案的智能補全',
      'Devin（雲端 Agent）：在雲端沙盒中自主執行開發任務，支援 terminal 操作',
      'Agent Command Center：統一管理多個平行 agent 任務的控制中心',
      'Spaces：儲存 codebase context，讓 AI 記住專案結構與偏好',
      'Windsurf Previews：即時預覽 UI 變更，整合 browser preview',
      'MCP 支援：連接外部工具、資料來源與自訂整合',
      'Supercomplete：多行、跨函式的進階程式碼補全',
    ],
    recentUpdates: [
      '2026/05/17 — v2.3.9 發布，修復多項 Cascade 與補全穩定性問題',
      '2026/05/12 — 支援 Claude Opus 4.7 fast mode，大幅提升回應速度',
      '2026/05/06 — v2.2.17 發布，Devin 整合改進與 MCP 穩定性提升',
      '2026/04/28 — Devin in Terminal 功能推出，可在終端直接呼叫雲端 agent',
    ],
    score: 0, delta: 0, discussions: 0, growth: '',
    sources: { reddit: 0, hn: 0, github: 0 },
    audiences: [], useCases: [], painPoints: [],
    pricingFeel: '', quotes: [], competitors: [], trend: [],
  },
  {
    rank: 0, prevRank: 0,
    slug: 'codex', name: 'Codex', initials: 'Cx',
    accent: 'oklch(0.52 0.12 240)', category: '程式開發',
    website: 'https://chatgpt.com/codex',
    logo_url: 'https://www.google.com/s2/favicons?domain=openai.com&sz=64',
    docsUrl: 'https://platform.openai.com/docs/codex',
    description: 'OpenAI 推出的雲端 coding agent，在沙盒環境平行處理多個任務並自動建立 PR',
    pricingDescription: 'ChatGPT Pro（$200/mo）用戶可直接使用。API 另計，o3 模型約 $10/1M input tokens。任務複雜度高時費用難以預測。',
    features: [
      '雲端沙盒隔離執行：每個任務在獨立環境中執行，不影響本地或生產環境',
      '平行多工：同時執行多個 coding task，任務互不干擾',
      '自動建立 GitHub PR，附帶變更說明與測試結果',
      '全 codebase 理解：直接整合 GitHub repo，讀取完整程式結構',
      '終端指令 + 測試套件執行：可安裝套件、跑測試、驗證結果',
      '以 o3 模型為核心，具備強推理與 debug 能力',
      '整合 ChatGPT 介面，可在 ChatGPT.com 直接指派任務',
    ],
    recentUpdates: [
      '2025/05 — 向 ChatGPT Pro、Plus、Team 用戶開放 Codex',
      '2025/05 — 加入 GitHub Actions 整合，支援 CI 自動化流程',
      '2025/04 — 正式推出（取代舊版 Codex API），支援 GitHub repo 綁定',
      '2025/04 — Enterprise 方案開放，提供更高任務配額與私有 repo 支援',
    ],
    score: 0, delta: 0, discussions: 0, growth: '',
    sources: { reddit: 0, hn: 0, github: 0 },
    audiences: [], useCases: [], painPoints: [],
    pricingFeel: '', quotes: [], competitors: [], trend: [],
  },
  {
    rank: 0, prevRank: 0,
    slug: 'github-copilot', name: 'GitHub Copilot', initials: 'GC',
    accent: 'oklch(0.45 0.03 260)', category: '程式開發',
    website: 'https://github.com/features/copilot',
    logo_url: 'https://www.google.com/s2/favicons?domain=github.com&sz=64',
    description: 'GitHub 與 OpenAI 合作的 AI 編碼助手，提供行內補全、Chat 與 Agent 模式，深度整合於 VS Code、JetBrains、Visual Studio',
    pricingDescription: '免費版含每月有限補全與 Chat 次數。Pro $10/mo、Pro+ $39/mo（含進階模型額度）。Business $19/user/mo，Enterprise $39/user/mo。',
    features: [
      '行內補全：邊打邊建議整行或整段程式碼',
      'Copilot Chat：在編輯器內以對話方式詢問與重構',
      'Agent Mode：自主跨多檔案完成任務並執行指令',
      '多模型選擇：可切換 GPT、Claude、Gemini 等模型',
      'Code Review：對 PR 自動產生審查建議',
      '跨 IDE 支援：VS Code / JetBrains / Visual Studio / Neovim',
    ],
    score: 0, delta: 0, discussions: 0, growth: '',
    sources: { reddit: 0, hn: 0, github: 0 },
    audiences: [], useCases: [], painPoints: [],
    pricingFeel: '', quotes: [], competitors: [], trend: [],
  },
  {
    rank: 0, prevRank: 0,
    slug: 'replit', name: 'Replit', initials: 'Rp',
    accent: 'oklch(0.62 0.18 35)', category: '程式開發',
    website: 'https://replit.com',
    logo_url: 'https://www.google.com/s2/favicons?domain=replit.com&sz=64',
    description: '雲端 IDE，內建 Replit Agent 可從自然語言直接生成、執行並一鍵部署全端應用，免設定本機環境',
    pricingDescription: '免費版含基礎運算與有限 Agent 試用。Core $20/mo（含每月 Agent 點數與更多運算）。Teams $35/user/mo。',
    features: [
      'Replit Agent：自然語言描述即建構完整應用',
      '雲端即時部署：寫完直接上線，附網域與託管',
      '多人即時協作：類 Google Docs 的共同編輯',
      '50+ 語言支援：免本機設定的開箱即用環境',
      '行動 App 開發：手機也能編碼與發布',
    ],
    score: 0, delta: 0, discussions: 0, growth: '',
    sources: { reddit: 0, hn: 0, github: 0 },
    audiences: [], useCases: [], painPoints: [],
    pricingFeel: '', quotes: [], competitors: [], trend: [],
  },
  {
    rank: 0, prevRank: 0,
    slug: 'aider', name: 'Aider', initials: 'Ai',
    accent: 'oklch(0.58 0.14 145)', category: '程式開發',
    website: 'https://aider.chat',
    logo_url: 'https://www.google.com/s2/favicons?domain=aider.chat&sz=64',
    description: '開源終端機 AI 結對程式設計工具，直接在本機 Git repo 中編輯多檔案並自動 commit，受重度終端使用者歡迎',
    pricingDescription: '工具本身完全免費開源，需自備 LLM API key（Claude、GPT、DeepSeek 等）按量計費。',
    features: [
      '終端機操作：在 CLI 中直接下指令改碼',
      '自動 Git commit：每次修改自動產生有意義的 commit',
      '多檔案編輯：跨檔案協調修改同一功能',
      'Repo map：自動建立專案上下文地圖',
      '支援多種 LLM：可搭配各家模型與本地模型',
      '語音輸入：可口述需求轉為程式修改',
    ],
    score: 0, delta: 0, discussions: 0, growth: '',
    sources: { reddit: 0, hn: 0, github: 0 },
    audiences: [], useCases: [], painPoints: [],
    pricingFeel: '', quotes: [], competitors: [], trend: [],
  },
  {
    rank: 0, prevRank: 0,
    slug: 'cline', name: 'Cline', initials: 'Cl',
    accent: 'oklch(0.55 0.16 230)', category: '程式開發',
    website: 'https://cline.bot',
    logo_url: 'https://www.google.com/s2/favicons?domain=cline.bot&sz=64',
    description: 'VS Code 內的開源自主編碼 Agent，可讀寫檔案、執行終端指令、操作瀏覽器完成任務，每步變更前需經使用者核可',
    pricingDescription: '擴充免費開源，需自備 API key（Anthropic、OpenRouter 等）按量計費，費用取決於所選模型。',
    features: [
      '自主檔案讀寫：理解專案後直接修改程式碼',
      '終端命令執行：可跑測試、安裝套件、建置',
      '瀏覽器操作：開網頁驗證結果與抓錯',
      'MCP 工具擴充：可自行接入外部工具',
      'Plan / Act 雙模式：先規劃再執行',
      '變更需核可：每步操作前由人確認',
    ],
    score: 0, delta: 0, discussions: 0, growth: '',
    sources: { reddit: 0, hn: 0, github: 0 },
    audiences: [], useCases: [], painPoints: [],
    pricingFeel: '', quotes: [], competitors: [], trend: [],
  },
  {
    rank: 0, prevRank: 0,
    slug: 'bolt', name: 'Bolt', initials: 'Bo',
    accent: 'oklch(0.6 0.18 55)', category: '程式開發',
    website: 'https://bolt.new',
    logo_url: 'https://www.google.com/s2/favicons?domain=bolt.new&sz=64',
    description: 'StackBlitz 推出的瀏覽器內 AI 全端開發環境，以 WebContainers 在瀏覽器直接執行 Node.js，對話即可生成並部署應用',
    pricingDescription: '免費版含每日 token 額度。付費由 $20/mo 起，依每月 token 用量分級。',
    features: [
      'WebContainers：瀏覽器內直接執行全端環境',
      '全端生成：前後端、套件、設定一次到位',
      '即時預覽：邊改邊看執行結果',
      '一鍵部署：可直接發布上線',
      'npm 套件支援：安裝並執行真實依賴',
      '錯誤自動修復：偵測執行錯誤並嘗試修正',
    ],
    score: 0, delta: 0, discussions: 0, growth: '',
    sources: { reddit: 0, hn: 0, github: 0 },
    audiences: [], useCases: [], painPoints: [],
    pricingFeel: '', quotes: [], competitors: [], trend: [],
  },
  {
    rank: 0, prevRank: 0,
    slug: 'lovable', name: 'Lovable', initials: 'Lo',
    accent: 'oklch(0.62 0.2 10)', category: '程式開發',
    website: 'https://lovable.dev',
    logo_url: 'https://www.google.com/s2/favicons?domain=lovable.dev&sz=64',
    description: '對話式生成全端 Web 應用的平台，內建 Supabase 整合與即時預覽，主打非工程師也能用自然語言打造產品',
    pricingDescription: '免費版含每日訊息額度。Pro $25/mo 起，依每月訊息量分級，另有 Teams 方案。',
    features: [
      '自然語言建構 UI：描述需求即生成介面',
      'Supabase 後端整合：資料庫與驗證一鍵接上',
      'GitHub 同步：程式碼可雙向同步到 repo',
      '即時預覽：所見即所得地調整',
      '一鍵發布：附託管與自訂網域',
      '響應式設計：自動適配桌機與行動裝置',
    ],
    score: 0, delta: 0, discussions: 0, growth: '',
    sources: { reddit: 0, hn: 0, github: 0 },
    audiences: [], useCases: [], painPoints: [],
    pricingFeel: '', quotes: [], competitors: [], trend: [],
  },
  {
    rank: 0, prevRank: 0,
    slug: 'devin', name: 'Devin', initials: 'Dv',
    accent: 'oklch(0.5 0.14 280)', category: '程式開發',
    website: 'https://devin.ai',
    logo_url: 'https://www.google.com/s2/favicons?domain=devin.ai&sz=64',
    description: 'Cognition 推出的自主 AI 軟體工程師，具備完整開發環境，可獨立規劃並完成端到端開發任務、提交 PR',
    pricingDescription: 'Core 方案按 ACU（Agent Compute Unit）用量計費；Team 方案 $500/mo 起含固定額度與多席位。',
    features: [
      '自主任務規劃：將需求拆解為可執行步驟',
      '完整開發環境：內建 shell、編輯器、瀏覽器',
      '平行任務：可同時推進多個工作',
      'Slack 整合：在對話中指派與回報進度',
      'PR 自動提交：完成後開 Pull Request',
    ],
    score: 0, delta: 0, discussions: 0, growth: '',
    sources: { reddit: 0, hn: 0, github: 0 },
    audiences: [], useCases: [], painPoints: [],
    pricingFeel: '', quotes: [], competitors: [], trend: [],
  },
  {
    rank: 0, prevRank: 0,
    slug: 'n8n', name: 'n8n', initials: 'n8',
    accent: 'oklch(0.62 0.2 30)', category: '自動化',
    website: 'https://n8n.io',
    logo_url: 'https://www.google.com/s2/favicons?domain=n8n.io&sz=64',
    docsUrl: 'https://docs.n8n.io',
    description: '開源工作流自動化平台，可視化串接 400+ 服務，支援自架或雲端，內建 AI Agent 節點',
    pricingDescription: '自架完全免費（社群版）。雲端 Starter $20/mo（2,500 workflow executions）、Pro $50/mo、Enterprise 客製。自架無執行次數限制是核心優勢。',
    features: [
      '400+ 內建整合節點：Slack、GitHub、Google Sheets、PostgreSQL 等一鍵串接',
      'AI Agent 節點：直接在工作流中呼叫 LLM、工具呼叫與記憶體管理',
      '可視化流程編輯器：拖拉節點建立複雜自動化，支援分支與迴圈',
      'Code 節點：隨時插入 JavaScript / Python 處理自訂邏輯',
      'Webhook 觸發：接收外部 HTTP 請求啟動工作流',
      '自架完全免費：Docker 一鍵部署，資料完全自主',
      'Sub-workflows：工作流可呼叫其他工作流，支援模組化設計',
      'Error handling：內建錯誤捕捉與重試機制',
    ],
    recentUpdates: [
      '2026/05 — n8n 2.0 正式發布：安全性全面重構，版本歷史支援並排比對',
      '2026/03 — Chat 節點新增 Human-in-the-Loop Actions，支援內聯審批按鈕',
      '2026/02 — Security & Policies 設定區上線，可強制 2FA 與管控個人空間',
      '2025/12 — SQLite 連線池優化，大型 instance 工作流載入速度提升 30–80%',
    ],
    score: 0, delta: 0, discussions: 0, growth: '',
    sources: { reddit: 0, hn: 0, github: 0 },
    audiences: [], useCases: [], painPoints: [],
    pricingFeel: '', quotes: [], competitors: [], trend: [],
  },
  {
    rank: 0, prevRank: 0,
    slug: 'make', name: 'Make', initials: 'Mk',
    accent: 'oklch(0.5 0.22 290)', category: '自動化',
    website: 'https://make.com',
    logo_url: 'https://www.google.com/s2/favicons?domain=make.com&sz=64',
    docsUrl: 'https://www.make.com/en/help',
    description: '前身 Integromat，視覺化流程自動化平台，以直觀的流程圖介面著稱，1,000+ 服務整合',
    pricingDescription: '免費版 1,000 ops/月。Core $9/mo（10,000 ops），Pro $16/mo（10,000 ops + 進階功能），Teams $29/mo。Ops 用量多時費用線性增加。',
    features: [
      '視覺化流程圖：以直觀的圓形節點與路由線設計工作流，比 Zapier 更靈活',
      '1,000+ 應用整合：Slack、Google、Notion、OpenAI、HubSpot 等一應俱全',
      'Router 節點：單一觸發可分流至多條平行路徑處理',
      'Iterator / Aggregator：批次處理陣列資料，適合大量資料轉換',
      'HTTP / Webhook：直接呼叫任意 API，不受限於現有整合',
      'Error handling：精細的錯誤捕捉、重試與備用路徑設定',
      'Data Store：內建輕量資料庫，儲存工作流中間狀態',
      'Scheduling：靈活排程，支援每分鐘到每月的各種觸發頻率',
    ],
    recentUpdates: [
      '2026/04 — Maia 上線：用自然語言建立自動化 Scenario，內建 AI Web Search 模組',
      '2026/03 — Make Grid 更新：全景自動化工作區，可即時編輯與洞察',
      '2026/02 — Rollover Operations：付費方案未用 ops 自動滾存至下月',
      '2026/01 — Make CLI 開放所有用戶；內建 Anthropic Claude 連接器',
    ],
    score: 0, delta: 0, discussions: 0, growth: '',
    sources: { reddit: 0, hn: 0, github: 0 },
    audiences: [], useCases: [], painPoints: [],
    pricingFeel: '', quotes: [], competitors: [], trend: [],
  },
  {
    rank: 0, prevRank: 0,
    slug: 'zapier', name: 'Zapier', initials: 'Zp',
    accent: 'oklch(0.62 0.22 35)', category: '自動化',
    website: 'https://zapier.com',
    logo_url: 'https://www.google.com/s2/favicons?domain=zapier.com&sz=64',
    docsUrl: 'https://help.zapier.com',
    description: '自動化工具市場龍頭，7,000+ 應用整合，no-code 設定門檻最低，適合非技術用戶',
    pricingDescription: '免費版 100 tasks/月（單步驟 Zap）。Professional $19.99/mo（750 tasks），Team $69/mo，Company $103/mo。Task 用量超出需升級或加購。',
    features: [
      '7,000+ 應用整合：覆蓋市場上幾乎所有 SaaS 工具',
      'Zap 自動化：觸發→動作的直觀設定，無需技術背景',
      'Multi-step Zaps：串接多個動作，支援條件判斷與篩選',
      'Paths：根據條件走不同處理流程（類似 Make Router）',
      'Tables：內建試算表資料庫，與 Zap 直接整合',
      'Interfaces：建立簡單的表單與 UI 觸發自動化',
      'AI Actions：自然語言描述想做的事，AI 自動配置步驟',
      'Zap 範本庫：數千個現成範本，一鍵複製修改',
    ],
    recentUpdates: [
      '2026/04 — AI Guardrails 上線：內建 AI 安全檢查，結構化輸出可搭配路由控制',
      '2026/03 — Agents 範本整合進 Templates Hub，一鍵瀏覽與啟動',
      '2026/02 — 自訂 Actions 支援 2,500+ 應用；Code 步驟執行時間延長',
      '2026/01 — Favorites 功能：可收藏 Zap、Table、Form 等所有資產',
    ],
    score: 0, delta: 0, discussions: 0, growth: '',
    sources: { reddit: 0, hn: 0, github: 0 },
    audiences: [], useCases: [], painPoints: [],
    pricingFeel: '', quotes: [], competitors: [], trend: [],
  },
  {
    rank: 0, prevRank: 0,
    slug: 'dify', name: 'Dify', initials: 'Df',
    accent: 'oklch(0.55 0.18 255)', category: '自動化',
    website: 'https://dify.ai',
    logo_url: 'https://www.google.com/s2/favicons?domain=dify.ai&sz=64',
    docsUrl: 'https://docs.dify.ai',
    description: '開源 LLM 應用開發平台，可視化建立 AI workflow、Chatbot 與 Agent，支援自架與雲端',
    pricingDescription: '自架完全免費（Apache 2.0）。雲端 Sandbox 免費（200 訊息/月），Professional $59/mo，Team $159/mo。自架無限制是核心優勢。',
    features: [
      'Workflow 編輯器：視覺化串接 LLM、工具與資料來源，建立複雜 AI 流程',
      'RAG Pipeline：內建文件解析、分塊、Embedding 與向量檢索全流程',
      '多模型支援：OpenAI、Anthropic、Google、本地 Ollama 模型一鍵切換',
      'Agent 模式：ReAct 框架讓 AI 自主規劃與呼叫工具',
      'Tool 整合：Google 搜尋、計算機、自訂 API 工具一鍵掛載',
      'Chatbot / Chatflow：直接部署對話式 AI 應用，可嵌入網站',
      'Prompt 管理：版本控制、A/B 測試與效能指標追蹤',
      '一鍵自架：Docker Compose 部署，完全掌控資料與模型',
    ],
    recentUpdates: [
      '2026/05 — v1.8.0：LLM 節點 Prompt 最佳化助手 + Code 節點自動修復功能',
      '2026/04 — MCP 用戶端支援：直連任意 MCP Server（GitHub、Slack、資料庫）',
      '2026/03 — Supervisor Agent 模式：協調多個 Sub-agent 處理複雜多步驟任務',
      '2026/01 — v1.0.0 Plugin 生態架構：模型與工具可獨立更新，無需升級整個平台',
    ],
    score: 0, delta: 0, discussions: 0, growth: '',
    sources: { reddit: 0, hn: 0, github: 0 },
    audiences: [], useCases: [], painPoints: [],
    pricingFeel: '', quotes: [], competitors: [], trend: [],
  },

  // ── 圖像生成 ────────────────────────────────────────────────
  {
    rank: 0, prevRank: 0,
    slug: 'midjourney', name: 'Midjourney', initials: 'MJ',
    accent: 'oklch(0.52 0.2 315)', category: '圖像生成',
    website: 'https://midjourney.com',
    logo_url: 'https://www.google.com/s2/favicons?domain=midjourney.com&sz=64',
    description: '目前社群公認美感最強的 AI 圖像生成器，Discord 指令介面，以風格多樣性與藝術質感著稱',
    pricingDescription: 'Basic $10/mo（200 張/月），Standard $30/mo（無限 relax），Pro $60/mo（無限 fast），Mega $120/mo（最大 GPU 優先權）。無免費方案。',
    features: [
      'v7 模型：業界最高美感評分，細節與光影渲染大幅提升',
      'Style Reference（--sref）：鎖定參考圖的風格，批量生成一致風格系列',
      'Character Reference（--cref）：跨圖保持同一角色一致性',
      'Vary Region：局部重繪，精準修改圖片特定區域',
      'Zoom Out / Pan：無限延伸畫布，擴展圖像邊界',
      '個人化風格（/tune）：訓練屬於你的自訂美感偏好',
    ],
    recentUpdates: [
      '2026/04 — v7 模型全面開放，Draft Mode 快速預覽',
      '2026/01 — Web 介面正式上線，告別純 Discord 操作',
      '2025/11 — Editor 功能：畫布式局部編輯與 Inpaint',
      '2025/09 — 個人化（Personalization）功能公開測試',
    ],
    score: 0, delta: 0, discussions: 0, growth: '',
    sources: { reddit: 0, hn: 0, github: 0 },
    audiences: [], useCases: [], painPoints: [],
    pricingFeel: '', quotes: [], competitors: [], trend: [],
  },
  {
    rank: 0, prevRank: 0,
    slug: 'gpt-image', name: 'GPT Image 2', initials: 'GI',
    accent: 'oklch(0.55 0.18 38)', category: '圖像生成',
    website: 'https://openai.com/research/gpt-image',
    logo_url: 'https://www.google.com/s2/favicons?domain=openai.com&sz=64',
    description: 'OpenAI 最新圖像生成產品，整合於 ChatGPT 與 API，以精準文字渲染、超寫實細節和多樣風格控制著稱，取代 DALL-E 3',
    pricingDescription: 'ChatGPT Plus/Pro 含每日限額圖像生成。API 計費（gpt-image-1）：標準 $0.04/張，HD $0.08/張。免費版 ChatGPT 有限制次數。',
    features: [
      'ChatGPT 整合：直接在對話中生成與編輯圖像，無需切換工具',
      '超精準文字渲染：圖像內嵌入清晰文字，超越前代 DALL-E 3',
      '多樣風格控制：照片寫實、插畫、3D 渲染等風格精準切換',
      'Inpainting：選取區域重新生成，保留其餘部分',
      '參考圖輸入：上傳圖片作為風格或構圖參考',
      'API 存取（gpt-image-1）：開發者直接整合進應用程式',
    ],
    recentUpdates: [
      '2026/04 — GPT Image 2 正式發布，取代 gpt-image-1',
      '2026/03 — gpt-image-1 API 開放，支援 Responses API 串流',
      '2026/01 — ChatGPT 圖像生成升級至新模型架構',
    ],
    score: 0, delta: 0, discussions: 0, growth: '',
    sources: { reddit: 0, hn: 0, github: 0 },
    audiences: [], useCases: [], painPoints: [],
    pricingFeel: '', quotes: [], competitors: [], trend: [],
  },
  {
    rank: 0, prevRank: 0,
    slug: 'comfyui', name: 'ComfyUI', initials: 'CF',
    accent: 'oklch(0.5 0.16 255)', category: '圖像生成',
    website: 'https://comfyui.com',
    logo_url: 'https://www.google.com/s2/favicons?domain=comfyui.com&sz=64',
    description: '最受進階用戶歡迎的開源 AI 圖像生成介面，以節點式工作流著稱，支援 Flux、SD、LoRA、ControlNet 等完整生成管線',
    pricingDescription: '本地自架完全免費（需 GPU）。Desktop 版 $49 買斷（含一鍵安裝、自動更新）。Comfy Cloud 雲端方案：Standard / Creator / Pro 三檔，2026/01 降價 30%，Pro 含每月 22hr GPU 時數。',
    features: [
      '節點式工作流：拖拉連接每個生成步驟，完全視覺化且可重現',
      '支援主流模型：Flux.1、SD 1.5、SDXL、SD 3.5 一鍵切換',
      'LoRA / ControlNet：精細控制人物、姿態、風格，生態豐富',
      'Inpaint / Outpaint：局部修補與邊界延伸節點',
      '工作流分享：社群大量分享 `.json` 工作流，直接匯入使用',
      'API 模式：無頭執行，可整合進自動化腳本與後端服務',
    ],
    recentUpdates: [
      '2026/03 — ComfyUI Desktop 正式版發布，一鍵安裝免手動配置',
      '2026/01 — 原生支援 Flux 1.1 Pro Ultra 與 Redux',
      '2025/10 — ComfyUI Manager：一鍵安裝社群自訂節點包',
    ],
    score: 0, delta: 0, discussions: 0, growth: '',
    sources: { reddit: 0, hn: 0, github: 0 },
    audiences: [], useCases: [], painPoints: [],
    pricingFeel: '', quotes: [], competitors: [], trend: [],
  },
  {
    rank: 0, prevRank: 0,
    slug: 'adobe-firefly', name: 'Adobe Firefly', initials: 'AF',
    accent: 'oklch(0.55 0.22 28)', category: '圖像生成',
    website: 'https://firefly.adobe.com',
    logo_url: 'https://www.google.com/s2/favicons?domain=adobe.com&sz=64',
    description: 'Adobe 出品的商業安全 AI 圖像生成器，以 Adobe Stock 授權素材訓練，完全可商用，深度整合 Photoshop 與 Illustrator',
    pricingDescription: '免費版含基礎生成。獨立方案：Standard $9.99/mo、Pro $19.99/mo、Pro Plus $49.99/mo、Premium $199.99/mo（含 50,000 credits）。Creative Cloud 訂閱另含 Generative Fill 使用額度。',
    features: [
      '商業安全：以 Adobe Stock 授權圖片訓練，生成內容可完全商用',
      'Generative Fill（Photoshop）：全球使用最廣的 AI 局部修圖功能',
      'Generative Expand：一鍵智慧延伸畫布',
      'Text to Vector（Illustrator）：文字生成可縮放向量圖形',
      'Structure Reference：控制圖像構圖結構，保持版面一致',
      'Content Credentials：AI 生成標記，符合 CAI 業界規範',
    ],
    recentUpdates: [
      '2026/05 — Firefly Image 4 Ultra：業界最高解析度與細節',
      '2026/02 — Firefly Video 正式推出',
      '2025/11 — Photoshop Generative Fill 整合 Firefly 3',
    ],
    score: 0, delta: 0, discussions: 0, growth: '',
    sources: { reddit: 0, hn: 0, github: 0 },
    audiences: [], useCases: [], painPoints: [],
    pricingFeel: '', quotes: [], competitors: [], trend: [],
  },
  {
    rank: 0, prevRank: 0,
    slug: 'ideogram', name: 'Ideogram', initials: 'Ig',
    accent: 'oklch(0.52 0.17 195)', category: '圖像生成',
    website: 'https://ideogram.ai',
    logo_url: 'https://www.google.com/s2/favicons?domain=ideogram.ai&sz=64',
    description: '以文字渲染和設計感著稱的 AI 圖像生成工具，最擅長製作含文字的海報、Logo、貼圖等設計類內容',
    pricingDescription: '免費版每天 10 prompts（約 40 張）。Basic $7/mo（400 prompts），Plus $15/mo（1000 prompts），Pro $42/mo（3000 prompts）。年繳可省 25–30%。',
    features: [
      '文字渲染 #1：在圖像中嵌入清晰可讀文字，遠超其他模型',
      'Magic Prompt：自動優化你的提示詞，提升生成品質',
      'Style Presets：設計感預設風格一鍵套用（插畫、3D、攝影等）',
      'Remix：以現有圖像為基礎再創作',
      'Canvas：局部修改與延伸生成',
      'Ideogram 2.0：更強的解剖結構與色彩理解',
    ],
    recentUpdates: [
      '2025/12 — Ideogram 2.0 Turbo：速度提升 3 倍',
      '2025/08 — API 開放，第三方整合',
      '2025/06 — Canvas 畫布編輯功能上線',
    ],
    score: 0, delta: 0, discussions: 0, growth: '',
    sources: { reddit: 0, hn: 0, github: 0 },
    audiences: [], useCases: [], painPoints: [],
    pricingFeel: '', quotes: [], competitors: [], trend: [],
  },
  {
    rank: 0, prevRank: 0,
    slug: 'leonardo-ai', name: 'Leonardo AI', initials: 'La',
    accent: 'oklch(0.5 0.17 300)', category: '圖像生成',
    website: 'https://leonardo.ai',
    logo_url: 'https://www.google.com/s2/favicons?domain=leonardo.ai&sz=64',
    description: '針對遊戲開發者與創意設計師的 AI 圖像平台，擁有豐富的微調模型庫、角色一致性功能與 Canvas 編輯器',
    pricingDescription: '免費版每天 150 credits（重置）。Apprentice $12/mo（8,500 credits/月），Artisan $30/mo（25,000 credits/月），Maestro $60/mo（60,000 credits/月）。年繳可省約 20%。',
    features: [
      '龐大微調模型庫：社群貢獻的遊戲角色、概念藝術、動漫等特化模型',
      'Phoenix 模型：Leonardo 自研旗艦模型，媲美 Midjourney 美感',
      'Motion：靜止圖像生成短影片',
      'Canvas 編輯器：Inpaint、Outpaint、元素精準控制',
      'Real-time Generation：打字同時即時預覽生成結果',
      'Character Consistency：跨圖保持人物外觀一致性',
    ],
    recentUpdates: [
      '2026/03 — Phoenix 1.5 模型：寫實與藝術風格大幅提升',
      '2025/11 — Alchemy V2：細節精修與高解析後處理',
      '2025/08 — 3D Texture Generation 功能上線',
    ],
    score: 0, delta: 0, discussions: 0, growth: '',
    sources: { reddit: 0, hn: 0, github: 0 },
    audiences: [], useCases: [], painPoints: [],
    pricingFeel: '', quotes: [], competitors: [], trend: [],
  },

  // ── 影片生成 ─────────────────────────────────────────────────
  {
    rank: 0, prevRank: 0,
    slug: 'seedance', name: 'Seedance', initials: 'Sd',
    accent: 'oklch(0.52 0.18 175)', category: '影片生成',
    website: 'https://seed.bytedance.com/en/seedance2_0',
    logo_url: 'https://www.google.com/s2/favicons?domain=bytedance.com&sz=64',
    description: 'ByteDance Seed 團隊推出的 AI 影片生成模型，2.0 版整合於 CapCut / Dreamina，支援 4K 60fps、多模態輸入與長片段角色一致性',
    pricingDescription: '透過 CapCut / Dreamina 提供服務，免費層含基礎生成次數。付費方案從 $20/mo 起。API 透過 fal.ai 按量計費。',
    features: [
      '4K 60fps 輸出：業界最高規格影片品質之一',
      '多模態輸入：文字、圖片、音訊、影片均可作為生成參考',
      '長片段一致性：跨多分鐘影片保持人物、場景、風格連貫',
      'Director-level 控制：燈光、陰影、攝影機運動、節奏精細調控',
      'Content ID for AI：防止生成名人樣貌或侵權電影風格的保護機制',
      'CapCut 整合：直接在 CapCut 剪輯流程中生成與套用',
    ],
    recentUpdates: [
      '2026/03 — Seedance 2.0 透過 CapCut Dreamina 正式推出',
      '2026/04 — Seedance 2.0 API 上線 fal.ai，開放開發者整合',
      '2025/12 — Seedance 1.0 發布，首次對外公開',
    ],
    score: 0, delta: 0, discussions: 0, growth: '',
    sources: { reddit: 0, hn: 0, github: 0 },
    audiences: [], useCases: [], painPoints: [],
    pricingFeel: '', quotes: [], competitors: [], trend: [],
  },
  {
    rank: 0, prevRank: 0,
    slug: 'kling', name: '可靈 Kling 3.0', initials: 'KL',
    accent: 'oklch(0.52 0.2 28)', category: '影片生成',
    website: 'https://klingai.com',
    logo_url: 'https://www.google.com/s2/favicons?domain=klingai.com&sz=64',
    description: '快手推出的 AI 影片生成平台，3.0 版本支援最長 15 秒、原生 4K、AI 自動分鏡導演系統，並加入 5 語言音訊生成',
    pricingDescription: '免費版含每日有限次數。付費方案依地區定價，API 另行計費。國際版（klingai.com）與中國版（可靈）功能略有差異。',
    features: [
      'Video 3.0：最長 15 秒連續影片，原生 4K 高清輸出',
      'AI Director 系統：自動理解腳本、分配鏡頭角度、正反打切換',
      'Video 3.0 Omni：參考圖像角色特徵提取，保持跨場景一致性',
      'Image 3.0：同系列高解析度靜態圖生成，風格與影片一致',
      '原生音訊生成：支援 5 種語言與多種口音的音訊同步',
      '首尾幀控制：指定影片開頭與結尾畫面，確保敘事連貫',
    ],
    recentUpdates: [
      '2026/02 — 可靈 3.0 正式發布（Video 3.0 + Image 3.0 + Omni）',
      '2025/11 — 可靈 2.6：運動筆刷與攝影機控制升級',
      '2025/09 — 可靈 2.0：4K 解析度與 API 正式開放',
    ],
    score: 0, delta: 0, discussions: 0, growth: '',
    sources: { reddit: 0, hn: 0, github: 0 },
    audiences: [], useCases: [], painPoints: [],
    pricingFeel: '', quotes: [], competitors: [], trend: [],
  },
  {
    rank: 0, prevRank: 0,
    slug: 'runway', name: 'Runway', initials: 'Rw',
    accent: 'oklch(0.45 0.02 280)', category: '影片生成',
    website: 'https://runwayml.com',
    logo_url: 'https://www.google.com/s2/favicons?domain=runwayml.com&sz=64',
    description: 'Runway 的 Gen 系列 AI 影片生成與編輯平台，主打影視級創作，廣泛用於廣告與短片製作',
    pricingDescription: '免費版含有限額度。Standard $15/mo、Pro $35/mo、Unlimited $95/mo，另有 Enterprise 方案與 API。',
    features: [
      'Gen-4：文字 / 圖像轉影片，畫面細節更穩定',
      '角色與場景一致性：跨鏡頭維持人物與風格',
      'Motion Brush：以筆刷指定畫面運動方向',
      '影片編輯工具：去背、慢動作、擴展畫布',
      'API：可整合進自有製作流程',
    ],
    score: 0, delta: 0, discussions: 0, growth: '',
    sources: { reddit: 0, hn: 0, github: 0 },
    audiences: [], useCases: [], painPoints: [],
    pricingFeel: '', quotes: [], competitors: [], trend: [],
  },
  {
    rank: 0, prevRank: 0,
    slug: 'sora', name: 'Sora', initials: 'So',
    accent: 'oklch(0.55 0.15 200)', category: '影片生成',
    website: 'https://openai.com/sora',
    logo_url: 'https://www.google.com/s2/favicons?domain=openai.com&sz=64',
    description: 'OpenAI 的文字轉影片模型，可生成高擬真影片，整合於 ChatGPT 與獨立 Sora App，支援故事板與形象置入',
    pricingDescription: '隨 ChatGPT Plus（$20/mo）提供有限生成；Pro（$200/mo）含更高解析度、更長影片與更多並行數。',
    features: [
      '文字 / 圖像轉影片：由提示直接生成片段',
      'Storyboard：以時間軸編排多個鏡頭',
      'Remix：以既有影片為基礎重新混製',
      'Cameo：將個人形象置入生成內容',
      '社群動態：在 Sora App 探索與再創作',
    ],
    score: 0, delta: 0, discussions: 0, growth: '',
    sources: { reddit: 0, hn: 0, github: 0 },
    audiences: [], useCases: [], painPoints: [],
    pricingFeel: '', quotes: [], competitors: [], trend: [],
  },
  {
    rank: 0, prevRank: 0,
    slug: 'pika', name: 'Pika', initials: 'Pk',
    accent: 'oklch(0.6 0.2 320)', category: '影片生成',
    website: 'https://pika.art',
    logo_url: 'https://www.google.com/s2/favicons?domain=pika.art&sz=64',
    description: 'Pika 的 AI 影片生成平台，以趣味特效 Pikaffects 與快速生成著稱，主打社群與創意短影音',
    pricingDescription: '免費版含基礎點數。付費 Standard $8/mo 起，至 Pro / Fancy 分級提供更高解析度與生成數。',
    features: [
      '文字 / 圖像轉影片：快速產出短片段',
      'Pikaffects：誇張趣味的物理特效',
      'Pikadditions：將物件置入既有影片',
      'Pikaframes：以關鍵幀控制過場',
      '唇形同步：為角色加上對嘴口型',
    ],
    score: 0, delta: 0, discussions: 0, growth: '',
    sources: { reddit: 0, hn: 0, github: 0 },
    audiences: [], useCases: [], painPoints: [],
    pricingFeel: '', quotes: [], competitors: [], trend: [],
  },
  {
    rank: 0, prevRank: 0,
    slug: 'veo', name: 'Veo', initials: 'Ve',
    accent: 'oklch(0.55 0.16 255)', category: '影片生成',
    website: 'https://deepmind.google/technologies/veo',
    logo_url: 'https://www.google.com/s2/favicons?domain=deepmind.google&sz=64',
    description: 'Google DeepMind 的文字轉影片模型，原生支援音訊生成，整合於 Gemini App 與 Flow 影片創作工具',
    pricingDescription: '隨 Google AI Pro / Ultra 訂閱提供生成額度，另可透過 Vertex AI 按量計費供企業使用。',
    features: [
      '文字 / 圖像轉影片：高品質寫實畫面',
      '原生音訊：同步生成對白、音效與環境音',
      '4K 輸出：高解析度影片產出',
      'Flow 工具：場景延伸與鏡頭編排',
      '運鏡控制：指定攝影機運動與構圖',
    ],
    score: 0, delta: 0, discussions: 0, growth: '',
    sources: { reddit: 0, hn: 0, github: 0 },
    audiences: [], useCases: [], painPoints: [],
    pricingFeel: '', quotes: [], competitors: [], trend: [],
  },
  {
    rank: 0, prevRank: 0,
    slug: 'hailuo', name: 'Hailuo', initials: 'Hl',
    accent: 'oklch(0.55 0.18 165)', category: '影片生成',
    website: 'https://hailuoai.video',
    logo_url: 'https://www.google.com/s2/favicons?domain=hailuoai.video&sz=64',
    description: 'MiniMax 海螺 AI 的影片生成模型，以動作流暢與高性價比受歡迎，支援鏡頭控制與角色參考',
    pricingDescription: '免費版含每日生成額度。付費方案依點數分級，API 另行按量計費。',
    features: [
      '文字 / 圖像轉影片：流暢自然的動態表現',
      'Director 鏡頭控制：指定運鏡與構圖',
      '角色參考一致性：依參考圖維持人物樣貌',
      '多語介面：中英等多語操作',
      'API：可整合進自有應用',
    ],
    score: 0, delta: 0, discussions: 0, growth: '',
    sources: { reddit: 0, hn: 0, github: 0 },
    audiences: [], useCases: [], painPoints: [],
    pricingFeel: '', quotes: [], competitors: [], trend: [],
  },

  // ── 寫作 ────────────────────────────────────────────────────
  {
    rank: 0, prevRank: 0,
    slug: 'chatgpt', name: 'ChatGPT', initials: 'CG',
    accent: 'oklch(0.55 0.15 155)', category: '寫作',
    website: 'https://chatgpt.com',
    logo_url: 'https://www.google.com/s2/favicons?domain=chatgpt.com&sz=64',
    description: '全球用戶最多的 AI 助理，以多輪對話、長文撰寫、摘要、翻譯與腦力激盪最廣泛使用',
    pricingDescription: '免費版含 GPT-4o mini 無限 + GPT-4o 限量。Plus $20/mo（GPT-4o 完整、o3 存取、Custom GPTs）。Team $30/user/mo，Enterprise 洽談。',
    features: [
      'GPT-4o：多模態旗艦模型，文字、圖像、語音一體',
      'o3 推理模型：深度思考，適合複雜分析與寫作潤飾',
      'Memory 記憶功能：跨對話記住你的偏好與背景',
      'Custom GPTs：針對特定寫作任務建立專屬助理',
      'Canvas 寫作模式：文件式介面，直接在段落上修改與批注',
      'Voice Mode：以語音對話方式腦力激盪與口述草稿',
    ],
    recentUpdates: [
      '2026/05 — GPT-4.1 正式上線，長文理解更精準',
      '2026/03 — Projects：跨對話保存文件與記憶的工作空間',
      '2026/01 — o3-mini 開放 Plus 用戶免費使用',
      '2025/11 — Canvas 寫作模式正式推出',
    ],
    score: 0, delta: 0, discussions: 0, growth: '',
    sources: { reddit: 0, hn: 0, github: 0 },
    audiences: [], useCases: [], painPoints: [],
    pricingFeel: '', quotes: [], competitors: [], trend: [],
  },
  {
    rank: 0, prevRank: 0,
    slug: 'notion-ai', name: 'Notion AI', initials: 'NA',
    accent: 'oklch(0.45 0.04 80)', category: '寫作',
    website: 'https://notion.so',
    logo_url: 'https://www.google.com/s2/favicons?domain=notion.so&sz=64',
    description: '深度整合在 Notion 工作空間的 AI 寫作助理，可對整個 workspace 提問、摘要頁面、起草文件，最適合重度 Notion 用戶',
    pricingDescription: 'Notion AI 為付費附加功能，$10/mo/user 或包含在 Business Plan（$18/mo）內。Plus Plan（$12/mo）不含 Notion AI，需額外購買。',
    features: [
      'AI 問答整個 Workspace：對所有頁面提問，像擁有個人知識庫助理',
      '頁面摘要：一鍵總結長文件、會議記錄',
      'AI 草稿：從標題一鍵生成完整段落，支援多種語氣與格式',
      '翻譯與改寫：保留原始格式直接翻譯或改變寫作風格',
      'Action Items 提取：從會議記錄自動列出待辦事項',
      '資料庫 AI 填充：批量生成資料庫欄位內容',
    ],
    recentUpdates: [
      '2026/04 — Notion AI 整合 Claude 3.7 模型',
      '2025/11 — AI Connectors：連接 Google Drive、Slack，跨平台問答',
      '2025/08 — Meeting Notes 自動轉錄與摘要',
    ],
    score: 0, delta: 0, discussions: 0, growth: '',
    sources: { reddit: 0, hn: 0, github: 0 },
    audiences: [], useCases: [], painPoints: [],
    pricingFeel: '', quotes: [], competitors: [], trend: [],
  },
  {
    rank: 0, prevRank: 0,
    slug: 'perplexity', name: 'Perplexity', initials: 'Pp',
    accent: 'oklch(0.52 0.16 215)', category: '寫作',
    website: 'https://perplexity.ai',
    logo_url: 'https://www.google.com/s2/favicons?domain=perplexity.ai&sz=64',
    description: 'AI 搜尋引擎與研究助理，每次回答都附來源引用，最適合需要即時資訊支撐的寫作研究與事實查核',
    pricingDescription: '免費版每日 5 次 Pro Search。Pro $20/mo（無限 Pro Search、多模型切換）。Max $200/mo（Perplexity Computer：19 個 AI 子代理協作的深度研究系統）。',
    features: [
      'Pro Search：深度研究模式，多輪搜尋後綜合成報告',
      '來源引用：每個論點附對應網頁連結，寫作引用更可信',
      '即時資訊：搜尋最新新聞與研究，不受訓練資料截止日限制',
      'Spaces：建立主題研究空間，上傳文件一起分析',
      '多模型選擇：Pro 用戶可切換 GPT-4o、Claude、Sonar',
      'Pages：將研究結果一鍵排版成可分享的精美頁面',
    ],
    recentUpdates: [
      '2026/05 — Deep Research：多步驟自動研究，生成長篇報告',
      '2026/02 — Perplexity Assistant：整合行事曆、郵件的 AI 助理',
      '2025/11 — Pages 功能：研究結果轉美觀發布頁',
    ],
    score: 0, delta: 0, discussions: 0, growth: '',
    sources: { reddit: 0, hn: 0, github: 0 },
    audiences: [], useCases: [], painPoints: [],
    pricingFeel: '', quotes: [], competitors: [], trend: [],
  },
  {
    rank: 0, prevRank: 0,
    slug: 'grammarly', name: 'Grammarly', initials: 'Gr',
    accent: 'oklch(0.52 0.18 145)', category: '寫作',
    website: 'https://grammarly.com',
    logo_url: 'https://www.google.com/s2/favicons?domain=grammarly.com&sz=64',
    description: '最廣泛使用的英文寫作潤飾工具，即時偵測語法、語氣、清晰度問題，在瀏覽器、Word、郵件全平台運作',
    pricingDescription: '免費版含基礎語法拼字。Pro $12/mo（進階語氣分析、風格建議、抄襲檢查）。Business $15/user/mo（團隊一致性功能）。',
    features: [
      '全平台 Extension：Chrome、Edge、Word、Outlook、Google Docs 無縫整合',
      '語氣偵測：分析文字語氣（自信、友善、正式），主動建議調整',
      'Clarity 建議：精簡冗長句子，提升可讀性',
      'Grammarly GO：AI 起草與改寫功能，不只是修改錯誤',
      '抄襲檢查：比對數十億網頁與學術資料庫',
      '風格指南：企業可設定品牌語言一致性規則',
    ],
    recentUpdates: [
      '2026/03 — Grammarly GO 2.0：更強的整段改寫與風格適配',
      '2025/10 — 支援更多語言的語氣分析',
      '2025/07 — Meeting 摘要功能整合 Zoom / Teams',
    ],
    score: 0, delta: 0, discussions: 0, growth: '',
    sources: { reddit: 0, hn: 0, github: 0 },
    audiences: [], useCases: [], painPoints: [],
    pricingFeel: '', quotes: [], competitors: [], trend: [],
  },
  {
    rank: 0, prevRank: 0,
    slug: 'jasper', name: 'Jasper AI', initials: 'Js',
    accent: 'oklch(0.52 0.19 290)', category: '寫作',
    website: 'https://jasper.ai',
    logo_url: 'https://www.google.com/s2/favicons?domain=jasper.ai&sz=64',
    description: '以行銷文案為核心的 AI 寫作平台，擁有 50+ 內容模板、品牌語調設定與團隊協作功能，適合行銷團隊規模化內容產出',
    pricingDescription: 'Creator $49/mo（1 用戶），Pro $69/mo（5 用戶，含品牌語調、10 個 Knowledge），Business 客製洽談。無長期免費版，有 7 天試用。',
    features: [
      '50+ 行銷模板：部落格、廣告文案、社群貼文、電子報等一鍵生成',
      'Brand Voice：輸入品牌資料，AI 學習並維持一致的語調與風格',
      'Knowledge Base：上傳產品文件，AI 寫作時自動參照',
      'Jasper Art：整合圖像生成，文圖搭配一站完成',
      'Campaign 規劃：從創意發想到多通路內容，全流程輔助',
      'SEO 整合：與 Surfer SEO 連動，即時優化關鍵字密度',
    ],
    recentUpdates: [
      '2026/04 — Jasper 2.0：重新設計介面，強化 Campaign 工作流',
      '2025/12 — 整合 Remix：多語言一鍵翻譯改寫',
      '2025/09 — AI 圖像功能升級至 Flux 模型',
    ],
    score: 0, delta: 0, discussions: 0, growth: '',
    sources: { reddit: 0, hn: 0, github: 0 },
    audiences: [], useCases: [], painPoints: [],
    pricingFeel: '', quotes: [], competitors: [], trend: [],
  },
  {
    rank: 0, prevRank: 0,
    slug: 'copy-ai', name: 'Copy.ai', initials: 'Ca',
    accent: 'oklch(0.52 0.18 225)', category: '寫作',
    website: 'https://copy.ai',
    logo_url: 'https://www.google.com/s2/favicons?domain=copy.ai&sz=64',
    description: '行銷內容自動化平台，以 GTM AI Workflow 連接 CRM 與內容工具，讓行銷團隊規模化產出銷售文案與潛客培育內容',
    pricingDescription: '免費版含每月 2000 字。Starter $49/mo，Advanced $249/mo（Workflow 自動化），Enterprise 洽談。定位從單人工具轉向企業自動化平台。',
    features: [
      'GTM AI Workflow：串接 HubSpot、Salesforce 自動生成銷售郵件與序列',
      '90+ 行銷模板：冷郵件、廣告文案、LinkedIn 貼文、產品描述',
      '潛客培育自動化：根據潛客資料個人化生成跟進內容',
      'Infobase：品牌資料中心，確保所有輸出符合品牌一致性',
      'Blog Wizard：從大綱到完整文章的一站式部落格生成',
      '多語言支援：25 種語言內容生成與翻譯',
    ],
    recentUpdates: [
      '2026/02 — GTM AI Platform 全面轉型，聚焦 B2B 自動化',
      '2025/10 — HubSpot 雙向整合，潛客資料自動同步',
      '2025/07 — Workflow 視覺化編輯器重大改版',
    ],
    score: 0, delta: 0, discussions: 0, growth: '',
    sources: { reddit: 0, hn: 0, github: 0 },
    audiences: [], useCases: [], painPoints: [],
    pricingFeel: '', quotes: [], competitors: [], trend: [],
  },

  // ── 語音 ────────────────────────────────────────────────────
  {
    rank: 0, prevRank: 0,
    slug: 'elevenlabs', name: 'ElevenLabs', initials: 'El',
    accent: 'oklch(0.5 0.12 295)', category: '語音',
    website: 'https://elevenlabs.io',
    logo_url: 'https://www.google.com/s2/favicons?domain=elevenlabs.io&sz=64',
    description: '語音 AI 的領導品牌，提供高擬真語音合成、語音克隆、AI 配音與對話式語音 Agent，廣泛用於有聲書與影音配音',
    pricingDescription: '免費版含每月有限字元。Starter $5/mo、Creator $22/mo、Pro $99/mo，企業另議，API 按用量計費。',
    features: [
      '文字轉語音：支援 30+ 語言的自然發音',
      '即時語音克隆：以少量樣本複製特定聲線',
      'AI 配音與翻譯：保留原聲音色的跨語配音',
      'Conversational AI：建構即時語音對話 Agent',
      '音效生成：由文字生成音效素材',
      'API：易於整合進產品與工作流',
    ],
    score: 0, delta: 0, discussions: 0, growth: '',
    sources: { reddit: 0, hn: 0, github: 0 },
    audiences: [], useCases: [], painPoints: [],
    pricingFeel: '', quotes: [], competitors: [], trend: [],
  },
  {
    rank: 0, prevRank: 0,
    slug: 'suno', name: 'Suno', initials: 'Su',
    accent: 'oklch(0.55 0.18 40)', category: '語音',
    website: 'https://suno.com',
    logo_url: 'https://www.google.com/s2/favicons?domain=suno.com&sz=64',
    description: 'AI 音樂生成平台，輸入文字即可生成含人聲、歌詞與配器的完整歌曲，是消費級 AI 作曲的代表',
    pricingDescription: '免費版每日有限額度。Pro $10/mo、Premier $30/mo，含商用授權與更多生成數。',
    features: [
      '文字轉歌曲：描述風格即生成完整歌曲',
      '人聲與歌詞：自動生成演唱與歌詞',
      '風格控制：指定曲風、情緒與樂器',
      'Stems 分軌：匯出人聲與伴奏分軌',
      '上傳延伸：以既有音訊為基礎續寫',
      '商用授權：付費方案含商業使用權',
    ],
    score: 0, delta: 0, discussions: 0, growth: '',
    sources: { reddit: 0, hn: 0, github: 0 },
    audiences: [], useCases: [], painPoints: [],
    pricingFeel: '', quotes: [], competitors: [], trend: [],
  },
  {
    rank: 0, prevRank: 0,
    slug: 'udio', name: 'Udio', initials: 'Ud',
    accent: 'oklch(0.55 0.17 300)', category: '語音',
    website: 'https://udio.com',
    logo_url: 'https://www.google.com/s2/favicons?domain=udio.com&sz=64',
    description: 'AI 音樂生成平台，主打高音質與細緻的曲風控制，常與 Suno 並列為兩大 AI 作曲工具',
    pricingDescription: '免費版含每月生成額度。Standard $10/mo、Pro $30/mo，含商用授權與優先生成。',
    features: [
      '文字轉音樂：由提示生成器樂與人聲',
      '高保真音質：偏向細緻的混音表現',
      'Inpainting：局部重繪修改片段',
      '曲風混合：融合多種風格與情緒',
      '分軌下載：匯出個別音軌',
      'Remix 與延伸：在既有作品上續作',
    ],
    score: 0, delta: 0, discussions: 0, growth: '',
    sources: { reddit: 0, hn: 0, github: 0 },
    audiences: [], useCases: [], painPoints: [],
    pricingFeel: '', quotes: [], competitors: [], trend: [],
  },
]

export const CATEGORIES: string[] = ['全部', '程式開發', '寫作', '圖像生成', '影片生成', '自動化', '語音']

export const SORTS: SortOption[] = [
  { id: 'hot', label: '話題熱度' },
  { id: 'rising', label: '本週上升' },
  { id: 'discussed', label: '最多討論' },
]
